export const EXPENSE_SUMMARY_MOCK_DATA = [
  {
    unspc: null,
    description: "Universal Ink Cyan",
    specification: "bottle",
    unitOfMeasure: "bottle",
    quantity: 3,
    price: "100",
  },
  {
    unspc: null,
    description: "Universal Ink Magenta",
    specification: "bottle",
    unitOfMeasure: "bottle",
    quantity: 3,
    price: "100",
  },
  {
    unspc: null,
    description: "Universal Ink Yellow",
    specification: "bottle",
    unitOfMeasure: "bottle",
    quantity: 3,
    price: "100",
  },
  {
    unspc: null,
    description: "Bond Paper Legal sub 20",
    specification: null,
    unitOfMeasure: "ream",
    quantity: 15,
    price: "240",
  },
  {
    unspc: null,
    description: "AIRCON (1.5 HORSE POWER)",
    specification: null,
    unitOfMeasure: "unit",
    quantity: 1,
    price: "30000",
  },
  {
    unspc: null,
    description: "CABINET (2 Doors, 4 layers)",
    specification: null,
    unitOfMeasure: "unit",
    quantity: 2,
    price: "12500",
  },
  {
    unspc: null,
    description: "Mesh wire",
    specification: null,
    unitOfMeasure: "unit",
    quantity: 4,
    price: "400",
  },
  {
    unspc: null,
    description: "HBC",
    specification: null,
    unitOfMeasure: "unit",
    quantity: 300,
    price: "15",
  },
  {
    unspc: "30111",
    description: "Cement",
    specification: null,
    unitOfMeasure: "unit",
    quantity: 6,
    price: "250",
  },
  {
    unspc: null,
    description: "Bamboo Poles",
    specification: null,
    unitOfMeasure: "unit",
    quantity: 6,
    price: "200",
  },
  {
    unspc: null,
    description: "Angle Bars 2mm",
    specification: null,
    unitOfMeasure: "unit",
    quantity: 10,
    price: "300",
  },
  {
    unspc: "23271",
    description: "Welding Rod",
    specification: null,
    unitOfMeasure: "unit",
    quantity: 2,
    price: "150",
  },
  {
    unspc: "11111",
    description: "Sand",
    specification: null,
    unitOfMeasure: "unit",
    quantity: 1,
    price: "2100",
  },
  {
    unspc: null,
    description: "Deformed Bars 10mm",
    specification: null,
    unitOfMeasure: "unit",
    quantity: 10,
    price: "160",
  },
  {
    unspc: null,
    description: "Spade",
    specification: null,
    unitOfMeasure: "unit",
    quantity: 2,
    price: "400",
  },
  {
    unspc: null,
    description: "Bolo",
    specification: null,
    unitOfMeasure: "unit",
    quantity: 2,
    price: "400",
  },
  {
    unspc: null,
    description: "Vegetable grow bags for gardening (polybag) 6x6x1",
    specification: null,
    unitOfMeasure: "unit",
    quantity: 3,
    price: "300",
  },
  {
    unspc: "23271",
    description: "Soldering iron",
    specification: null,
    unitOfMeasure: "unit",
    quantity: 1,
    price: "250",
  },
  {
    unspc: null,
    description: "Grass cutter",
    specification: null,
    unitOfMeasure: "unit",
    quantity: 2,
    price: "300",
  },
];
